<a href="https://colab.research.google.com/github/lelyashashlyk/DataScienceLearning/blob/main/pandas/pd_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np
import pandas as pd

# Task 1

Создайте датафрейм из рандомно сгенеренного нампай массива целых чисел 10х10 и имен колонок:



```
col = ['col_1', 'col_2', 'col_3', ....]
```

In [77]:
col_name = ['col_'+ str(i+1) for i in range(10)]
col_name

['col_1',
 'col_2',
 'col_3',
 'col_4',
 'col_5',
 'col_6',
 'col_7',
 'col_8',
 'col_9',
 'col_10']

In [78]:
df = pd.DataFrame(np.random.randint(100, size=(10,10)), columns = col_name)
df

   col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0     68     25     34     30     86     31     94     42     19      63
1     90     96     59     33      5     49     76     37     81      39
2     28      9      7     23     82     80     72     50     73      43
3     67     77     71     89     70     13     95     90     59      29
4     59     12     46     47     55     61     31     18     70      73
5     33     98     12     62     95     97     28     75     61      78
6     94      5     94     71      3     36      1     38     64      15
7     66     92     23     39     74      2     57     71     39      36
8     91     71      5     95     29     80     77     12     55      30
9      5      9     49     72     23     20     41     78     29      29

# Task 2

В колонках col_1, col_4, col_6 в трех рандомных строках значения сделайте пустыми (NaN). Постарайтесь этот процесс автоматизировать)

In [79]:
col = ['col_1', 'col_4', 'col_6']

In [80]:
for c in col:
  df[c].iloc[np.random.choice(df.index, 3)] = np.nan

/tmp/ipython-input-1259120753.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[c].iloc[np.random.choice(df.index, 3)] = np.nan
/tmp/ipython-input-1259120753.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[c].iloc[np.random.choice(df.index, 3)] = np.nan
/tmp/ipython-input-1259120753.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[c].iloc[np.random.choice(df.index, 3)] = np.nan
/tmp/ipython-input-1259120753.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[c].iloc[np.random.choice(df.index, 3)] = np.nan

In [81]:
df

   col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0    NaN     25     34    NaN     86   31.0     94     42     19      63
1   90.0     96     59   33.0      5    NaN     76     37     81      39
2   28.0      9      7   23.0     82   80.0     72     50     73      43
3    NaN     77     71   89.0     70    NaN     95     90     59      29
4   59.0     12     46   47.0     55    NaN     31     18     70      73
5    NaN     98     12   62.0     95   97.0     28     75     61      78
6   94.0      5     94   71.0      3   36.0      1     38     64      15
7   66.0     92     23    NaN     74    2.0     57     71     39      36
8   91.0     71      5   95.0     29   80.0     77     12     55      30
9    5.0      9     49    NaN     23   20.0     41     78     29      29

# Task 3

Отберите из датасета 4 рандомных строки и добавте в конец фрейма. (Синтезируем дупликаты.) Обновите индексы. Чтобы в сгенеренном массиве с индексами строк не было повторов, используйте следущую нампай функцию:



```
np.random.choice(10, 4, replace=False)
```

Пристыковать полученные строки в конец датафрейма можно с помощью функции concat:



```
pd.concat([df_1, df_2], axis=0)
```

In [82]:
df2 = pd.DataFrame(df.iloc[np.random.choice(10, 4, replace=False)])

In [83]:
df = pd.concat([df, df2], axis=0)

In [84]:
df = df.reset_index(drop=True)

In [85]:
df

    col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0     NaN     25     34    NaN     86   31.0     94     42     19      63
1    90.0     96     59   33.0      5    NaN     76     37     81      39
2    28.0      9      7   23.0     82   80.0     72     50     73      43
3     NaN     77     71   89.0     70    NaN     95     90     59      29
4    59.0     12     46   47.0     55    NaN     31     18     70      73
5     NaN     98     12   62.0     95   97.0     28     75     61      78
6    94.0      5     94   71.0      3   36.0      1     38     64      15
7    66.0     92     23    NaN     74    2.0     57     71     39      36
8    91.0     71      5   95.0     29   80.0     77     12     55      30
9     5.0      9     49    NaN     23   20.0     41     78     29      29
10    NaN     98     12   62.0     95   97.0     28     75     61      78
11    5.0      9     49    NaN     23   20.0     41     78     29      29
12    NaN     25     34    NaN     86   31.0     94     42     19      63
13   28.0      9      7   23.0     82   80.0     72     50     73      43

# Task 4

Получите нампай массив в котором будут степени заполненности по всем строкам.

In [86]:
df.isna().sum()

col_1     5
col_2     0
col_3     0
col_4     5
col_5     0
col_6     3
col_7     0
col_8     0
col_9     0
col_10    0
dtype: int64

In [87]:
np.array(df.isna().sum())

array([5, 0, 0, 5, 0, 3, 0, 0, 0, 0])

# Task 5

Удалите те строки, где количество пропусков от двух. Если один пропуск, то удаление не требуется.

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   9 non-null      float64
 1   col_2   14 non-null     int64
 2   col_3   14 non-null     int64
 3   col_4   9 non-null      float64
 4   col_5   14 non-null     int64
 5   col_6   11 non-null     float64
 6   col_7   14 non-null     int64
 7   col_8   14 non-null     int64
 8   col_9   14 non-null     int64
 9   col_10  14 non-null     int64
dtypes: float64(3), int64(7)
memory usage: 1.2 KB

In [89]:
t = df.shape[0]-5 # ?
df.dropna(axis=0, thresh=t)

    col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
1    90.0     96     59   33.0      5    NaN     76     37     81      39
2    28.0      9      7   23.0     82   80.0     72     50     73      43
4    59.0     12     46   47.0     55    NaN     31     18     70      73
5     NaN     98     12   62.0     95   97.0     28     75     61      78
6    94.0      5     94   71.0      3   36.0      1     38     64      15
7    66.0     92     23    NaN     74    2.0     57     71     39      36
8    91.0     71      5   95.0     29   80.0     77     12     55      30
9     5.0      9     49    NaN     23   20.0     41     78     29      29
10    NaN     98     12   62.0     95   97.0     28     75     61      78
11    5.0      9     49    NaN     23   20.0     41     78     29      29
13   28.0      9      7   23.0     82   80.0     72     50     73      43

In [90]:
df = df.dropna(axis=0, thresh=t)

# Task 6

Заполните все пропуски средними по соответствующим колонкам.

In [91]:
col_means = df.mean(axis=0)
col_means

col_1     51.777778
col_2     46.181818
col_3     33.000000
col_4     52.000000
col_5     51.454545
col_6     56.888889
col_7     47.636364
col_8     52.909091
col_9     57.727273
col_10    44.818182
dtype: float64

In [92]:
df.fillna(col_means)

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10
1,90.000000,96,59,33.0,5,56.888889,76,37,81,39
2,28.000000,9,7,23.0,82,80.000000,72,50,73,43
4,59.000000,12,46,47.0,55,56.888889,31,18,70,73
5,51.777778,98,12,62.0,95,97.000000,28,75,61,78
6,94.000000,5,94,71.0,3,36.000000,1,38,64,15
7,66.000000,92,23,52.0,74,2.000000,57,71,39,36
8,91.000000,71,5,95.0,29,80.000000,77,12,55,30
9,5.000000,9,49,52.0,23,20.000000,41,78,29,29
10,51.777778,98,12,62.0,95,97.000000,28,75,61,78
11,5.000000,9,49,52.0,23,20.000000,41,78,29,29
13,28.000000,9,7,23.0,82,80.000000,72,50,73,43

In [93]:
df = df.fillna(col_means)

# Task 7

Переименуйте первую колонку в 'user_id' и все элементы приведите к виду 'ID_15'.. Дробных значений чисел быть не должно.

In [94]:
df.index = df.index.rename('user_id')

In [95]:
df.index

Index([1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13], dtype='int64', name='user_id')

In [96]:
df.index = df.index.map(lambda x: 'ID_' + str(x+1))

In [97]:
df

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10
user_id,,,,,,,,,,
ID_2,90.000000,96,59,33.0,5,56.888889,76,37,81,39
ID_3,28.000000,9,7,23.0,82,80.000000,72,50,73,43
ID_5,59.000000,12,46,47.0,55,56.888889,31,18,70,73
ID_6,51.777778,98,12,62.0,95,97.000000,28,75,61,78
ID_7,94.000000,5,94,71.0,3,36.000000,1,38,64,15
ID_8,66.000000,92,23,52.0,74,2.000000,57,71,39,36
ID_9,91.000000,71,5,95.0,29,80.000000,77,12,55,30
ID_10,5.000000,9,49,52.0,23,20.000000,41,78,29,29
ID_11,51.777778,98,12,62.0,95,97.000000,28,75,61,78
ID_12,5.000000,9,49,52.0,23,20.000000,41,78,29,29
ID_14,28.000000,9,7,23.0,82,80.000000,72,50,73,43

# Task 8

Удалите повторы по строкам. Приведите индексы в порядок при необходимости.

In [98]:
df.drop_duplicates(inplace=True)
df.reset_index(inplace=True, drop=True)
df.index = df.index.map(lambda x: 'ID_' + str(x+1))

In [99]:
df

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10
ID_1,90.000000,96,59,33.0,5,56.888889,76,37,81,39
ID_2,28.000000,9,7,23.0,82,80.000000,72,50,73,43
ID_3,59.000000,12,46,47.0,55,56.888889,31,18,70,73
ID_4,51.777778,98,12,62.0,95,97.000000,28,75,61,78
ID_5,94.000000,5,94,71.0,3,36.000000,1,38,64,15
ID_6,66.000000,92,23,52.0,74,2.000000,57,71,39,36
ID_7,91.000000,71,5,95.0,29,80.000000,77,12,55,30
ID_8,5.000000,9,49,52.0,23,20.000000,41,78,29,29